### ISSUE TITLE
Transactions and AutoCommit ?

### ISSUE THREAD

**Issue by markddrake** [Teradata/nodejs-driver#17]
Is the driver in AUTO_COMMIT mode by default. If so, can I disable this. Can I use a cursor.execute to begin, commit and rollback transactions ?

**Comment by jeremysmartt** [comment]
Hello, take a look at these transaction tests:
https://github.com/Teradata/nodejs-driver/tree/ae9a140278c5f480574006e8b5284d8d566e965e/test/txn

In particular:
auto-commit-off-ddl.ts
auto-commit.ts
commit-and-rollback.ts

**Comment by markddrake** [comment]
Thanks, that seems to work, at least I can see the rows that have been commited from another connection while the insert process is still running, so I think it appears to be a safe assumption :)
