### ISSUE TITLE
Teradata shouldn't spawn sub-processes and arbitrarily execute shell commands

### ISSUE THREAD

**Issue by CharlieMartell** [Teradata/nodejs-driver#18]
In teradata-nodejs-driver install script [install-dependencies.js](https://github.com/Teradata/nodejs-driver/blob/develop/scripts/install-dependencies.js) it spawns a subprocess and runs an 'npm install' of a prebuilt package on your machine.

This is a bad, 
- It breaks applications using a different package manager than 'npm'
- It's assuming the desired runtime environment
- It is kind of an unwritten rule you shouldn't run shell commands against someones machine on installation of a package....

**Comment by adamtwo** [comment]
@CharlieMartell ,
fully agree with your comments. We have just released version 1.0.0-rc.5 that no longer modifies the parent package.json nor does it spawn any other process during install. The latest version relies on `require.resolve()` node.js API to resolve `@teradataprebuilt/nativelib` dependencies.
