### ISSUE TITLE
COP Discovery

### ISSUE THREAD

**Issue by ajgold15** [Teradata/nodejs-driver#24]
Is there a plan to implement COP discovery?

**Comment by ScriptPup** [comment]
Is this maintained anymore? It seems like it may not be given how long it's been since there was an update or response to any question.

**Comment by adamtwo** [comment]
The `@teradataprebuilt/nativelib` version `1.0.0-beta.3` that we published on Nov 8th 2021 supports COP discovery. If you depend on `teradata-nodejs-driver` version `1.0.0-rc.5` or higher you no longer need to code your own COP logic.
