### ISSUE TITLE
Library test cases unable to connect

### ISSUE THREAD

**Issue by pixeloution** [Teradata/nodejs-driver#29]
I've cloned the repo and done the following

* Ran `npm install` within `examples/javascript` - this ran without errors
* Updated the connection parameters in `src/connection.js`
* Attempted to run via `node src/connection.js`

Connection attempts are refused. I've validated my settings via Teradata Studio and can connect successfully to our instance. Any feedback on a resolution path would be appreciated.

```
node src/connection.js
[Version 42659830765e8ee7b720b821cd0b35677b82dbd5] [Session 0] [Teradata SQL Driver] Failed to connect to [REMOVED]:1025
 at gosqldriver/teradatasql.(*teradataConnection).makeDriverError TeradataConnection.go:1035
 at gosqldriver/teradatasql.newTeradataConnection TeradataConnection.go:135
 at gosqldriver/teradatasql.(*teradataDriver).Open TeradataDriver.go:32
 at database/sql.dsnConnector.Connect sql.go:600
 at database/sql.(*DB).conn sql.go:1103
 at database/sql.(*DB).Conn sql.go:1619
 at main.goCreateConnection goside.go:175
 at main.jsgoCreateConnection goside.go:135
 at main._cgoexpwrap_4778fd27be19_jsgoCreateConnection _cgo_gotypes.go:175
 at runtime.call64 asm_amd64.s:574
 at runtime.cgocallbackg1 cgocall.go:316
 at runtime.cgocallbackg cgocall.go:194
 at runtime.cgocallback_gofunc asm_amd64.s:826
 at runtime.goexit asm_amd64.s:2361
Caused by dial tcp [REMOVED]:1025: connect: operation timed out
```

**Comment by adamtwo** [comment]
@pixeloution,
sorry for the late response. What's the operating system and node version that you are using?

Adam

**Comment by adamtwo** [comment]
We have recently added a GH Actions workflow that executes integration tests. Please have a look at the setup to replicate on your local: https://github.com/Teradata/nodejs-driver/blob/develop/.github/workflows/ci-integration-tests.yml . 

If you need further assistance with testing please open another issue and indicate what setup you are using.
