### ISSUE TITLE
Teradata driver not working in docker node images

### ISSUE THREAD

**Issue by greekdude90** [Teradata/nodejs-driver#33]
Running locally on my windows machine, everything works fine, but when I try to deploy my app in a docker image, the Teradata driver fails inconsistently, as in it fails, but not in always in the same place, even with the same parameters being passed.

I've tested with node:16-buster-slim, lts-buster-slim, and lts-stretch.

Teradata version:  16.20.53.13

The code fails when calling fetchall.

Error and output @ log level 2:
pre fetchall
goFetchRow uRowsHandle=1 teradataRows=42659830765e8ee7b720b821cd0b35677b82dbd5 con=0xc42011a000 sess=75515911 stmt=0xc4200ec440 sql={fn teradata_rows_handle(1)}SELECT uid FROM DLCOMM_LABAdhoc.TestCases WHERE name = ?  rows=0xc4200e4480 noex=false fake=0 freed=true closed=false req=1 stmt=1 acttype=1 actcnt=1 params=0 cols=1
goFetchRow uRowsHandle=1 rows=&{0xc420126100 0x7fd1971b8b20 0xc4200e4480 0x7fd1971a79d0 <nil> {{0 0} 0 0 0 0} false <nil> []}
Rows.Next: iColumn=0 uCookedDataType=496 uColumnByteCount=4 uColumnScale=0 bPresent=true len(abyColumnValues)=4
goFetchRow column 1 of 1 type teradatasql.TeradataValue value 1300001
goFetchRow column 1 of 1 changed to type int32 value 1300001
goFetchRow returning nColumnValuesByteCount=6
goFetchRow returning pcColumnValues=0x61336d0
deserializing int

#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7fff7e3825e0
 1: 0xb6afe1  [node]
 2: 0x1bd40d4 V8_Fatal(char const*, ...) [node]
 3: 0xfcdeb1 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xd0e848 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xab6ff0 napi_get_typedarray_info [node]
 6: 0x7fd1a452e3af  [/home/node/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 7: 0x7fd1a452ebc8  [/home/node/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 8: 0x7fd1a452f4fb  [/home/node/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 9: 0x7fd1a453701b Napi::details::CallbackData<void (*)(Napi::CallbackInfo const&), void>::Wrapper(napi_env__*, napi_callback_info__*) [/home/node/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
10: 0xaadddf  [node]
11: 0xd432cb  [node]
12: 0xd4454a  [node]
13: 0xd44a26 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
14: 0x15c9fd9  [node]
Trace/breakpoint trap

connection parameters:
        var connParams = {
                log: '2',
                logmech: 'LDAP',
                tmode: 'TERA',
};

CODE:
``` js
function Query( query, values, connection, expectResultSet = false ){
        var rtv;
        console.log( 'in queru' );

        try{
                console.log( "pre cursor" );
                var cursor = connection.cursor();

                console.log( "pre execution" );
                cursor.execute( query, values );

                console.log( cursor );
                console.log( "pre fetchall" );
                rtv = cursor.fetchall();

                if( expectResultSet ){
                        while (true) {
                                console.log( "pre nextset" );
                                if( ! cursor.nextset() ){
                                        break;
                                }

                                rtv = cursor.fetchall();
                        }
                }
        }catch( e ){
                throw e;
        }

        console.log( 'done' );
        console.log( rtv );

        return rtv;
}
```

**Comment by crambelsoupy** [comment]
Hi @greekdude90, I am having the same issue. Have you been able to find any solution?

**Comment by adamtwo** [comment]
We are getting this error with higher node versions. The error doesn't occur with v12. It seems to be related to https://github.com/node-ffi-napi/node-ffi-napi/issues/125 . We will need to do more testing with more recent versions of node.js. I'm glad that you got it to work with v12.

**Comment by adamtwo** [comment]
Apart from the issues with worker threads, we are also monitoring https://github.com/node-ffi-napi/ref-napi/issues/54 that prevents us from running on Node.js > v12 even when work threads are not used.

**Comment by adamtwo** [comment]
Good news, node-ffi-napi/ref-napi#54 got resolved by a change in core Node.js. while v14 and v16 are still erroring out, v17 works out of the box. We are hoping that this will be the case for subsequent versions of node. Going forward, we will be testing the library with v12, v17 and subsequent releases.
