### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by ErikJansenIRefact** [Teradata/nodejs-driver#5]
Hi Jeremy,

I have taken a look into the software. We would like to use this driver in our NodeJS project.
I am wondering how we could contribute / collaborate in case we are running into issues, functional changes.

Any ideas / thoughts.

Kind regards,

Erik

**Comment by jeremysmartt** [comment]
Hello, 
This is an Open Source project maintained by Teradata.  However, we accept issues written by outside sources as well as Pull Requests.  So feel free to use the driver as well as submit these when needed.  Thanks! 👍

**Comment by ErikJansenIRefact** [comment]
Hi Jeremy,

We do need some guidelines/assistance in how the software is setup/works.
Do you think there’s some time for this? Especially the shared library. What’s inside? Which functions, …? What do they do? How is the shared library maintained? Etcetera.

Kind regards,

Erik Jansen | I-Refact
Bruistensingel 138 | 5232 AC | 's-Hertogenbosch
T +31 6 53 33 22 46 | erik.jansen@i-refact.com<mailto:erik.jansen@i-refact.com> | www.i-refact.com<htttp://www.i-refact.com/>


The information dispatched by this e-mail message is exclusively intended for the addressee.
The use of this information by others than the addressee is forbidden. Publication,
multiplication and/or spread of this information to third parties will not be allowed.
Though due care has been exercised with the dispatch of this e-mail message, a correct and
full transfer of this e-mail message cannot be guaranteed.
No rights can be derived from this e-mail message and/or files attached to this e-mail message.

**Comment by jeremysmartt** [comment]
The shared library is maintained internally by Teradata.  At the moment we are not open sourcing nor providing documentation on this shared library.  However, the main usage of this library is via our Node.js, R, and Python drivers.  The Node.js driver is open sourced and documented for usage.
