### ISSUE TITLE
Float Data Type and NAN, -INF and +INF

### ISSUE THREAD

**Issue by markddrake** [Teradata/nodejs-driver#52]
Does the teradata implimentation of FLOAT support NAN, INF and -INF. If so how would I supply these values to the node.js driver ?

**Comment by adamtwo** [comment]
@markddrake , Teradata Vantage does not support special FLOAT values like INF, -INF, or NaN. You can pass Javascript `NaN`, `Number.POSITIVE_INFINITY`, `Number.NEGATIVE_INFINITY` but the behavior is not specified. For example, for node.js and Vantage Express 17.10 I can insert and retrieve Number.POSITIVE_INFINITY, but `Number.NEGATIVE_INFINITY` and `NaN` generate:

```
[Error 2616] Numeric overflow occurred during computation.
```
