### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by kishorekpoluri** [Teradata/nodejs-driver#9]
Failed to connect to the database: caused by dial tcp: too many colons in address.

I'm following the same notation as I do for Java which never had issue.

host: 'jdbc:teradata://TDTT/TMODE=TERA,CHARSET=UTF8,',

Please advise. Thanks in advance.

**Comment by jeremysmartt** [comment]
@kishorekpoluri 
for the host you only need to put the hostname. In your example above I believe that is TDTT
so:
host: 'TDTT',
The `jdbc:teradata` syntax is only for the JDBC driver.
